---

- name: Configure Elsa Home Media Box
  hosts: elsamedia
  become: true

  tasks:
  - import_role:
      name: homepackages
    tags:
      - elsamedia
      - enablevnc
  - import_role:
      name: homeshares
    tags:
      - elsamedia
      - mountnas

   
