---

- name: install basic dev packages
  yum:
    name: "{{ elsa_dev_packages }}"
    state: present
    update_cache: yes
  when: ansible_facts['distribution'] == "CentOS"
  tags:
    - elsamedia
    - devpackages




