---

#- include_vars: vault.yml

- name: install gnome groups
  yum:
     name: "@Gnome Desktop"
     state: present
     update_cache: yes
  when: ansible_facts['distribution'] == "CentOS"
  tags:
    - elsamedia
    - enablevnc

- name: install tiger vnc
  yum:
     name: "tigervnc-server"
     state: present
     update_cache: yes
  when: ansible_facts['distribution'] == "CentOS"
  tags:
    - elsamedia
    - enablevnc

- name: create vnc user service
  template:
    src: vncserver_template.j2
    dest: /etc/systemd/system/vncserver@:1.service
  when: ansible_facts['distribution'] == "CentOS"
  tags:
    - elsamedia
    - enablevnc

- name: "Create the remote $HOME/.vnc directory"
  file:
    path: "/home/{{ vnc_user }}/.vnc"
    mode: 0750
    owner: "{{ vnc_user }}"
    state: directory

- name: "Generate vnc password for root user remotely"
  shell: |
    echo {{ vnc_password }} | vncpasswd -f > /home/{{ vnc_user }}/.vnc/passwd

- name: set firewall access for vnc
  shell: firewall-cmd --permanent --zone=public --add-service vnc-server && firewall-cmd --reload
  when: ansible_facts['distribution'] == "CentOS"
  tags:
    - elsamedia
    - enablevnc

- name: just force systemd to reread configs (2.4 and above)
  systemd:
    name: vncserver@:1.service
    enabled: yes
    daemon_reload: yes
  tags:
    - elsamedia
    - enablevnc

