---
share_mnt_root: '/mnt/netgear'

familylibrary_creds_path: '/root/familylibrary.creds'
familylibrary_mnt_path: 'FamilyLibrary'


cifs_shares:
 - { root_path: "{{ share_mnt_root }}",  path: "{{ share_mnt_root }}/{{ familylibrary_mnt_path }}", src: "{{ familylibrary_net_path }}", options: "vers=1.0,credentials={{ familylibrary_creds_path }},uid=48,gid=100,rw,nounix,iocharset=utf8,file_mode=0770,dir_mode=0770" }
