---
# tasks file for prometheus
#

- name: Add Prometheus User
  user:
    name: prometheus
    shell: /bin/bash

- name: Get Version 2.6 prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.6.0/prometheus-2.6.0.linux-amd64.tar.gz
    dest: /tmp
    checksum: sha256:8f1f9ca9dbc06e1dc99200e30526ca8343dfe80c2bd950847d22182953261c6c

- name: Extract prometheus into $HOME/prometheus
  unarchive:
    src: /tmp/prometheus-2.6.0.linux-amd64.tar.gz 
    dest: /home/prometheus/

- name: Rename Folder
  shell: mv prometheus-2.6.0.linux-amd64 prometheus
  args:
    chdir: /home/prometheus



  
